# Generated by Django 4.2.5 on 2023-11-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_color_product_colour_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cart'),
        ),
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='colour',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
