# Generated by Django 4.2.5 on 2023-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(default='www.null.com', max_length=255),
            preserve_default=False,
        ),
    ]
