# Generated by Django 4.2.5 on 2023-11-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_id_alter_colour_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='key',
        ),
        migrations.RemoveField(
            model_name='category',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='colour',
            name='key',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='key',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='size',
            name='key',
        ),
        migrations.RemoveField(
            model_name='size',
            name='stock',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preference',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
